server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: 1
    basic_auth:
      username: admin_loki_master_table
      password: xcRauS1Mg8vGYnC

scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]

    pipeline_stages:
    - replace:
        expression: '(?:[0-9]{1,3}\.){3}([0-9]{1,3})'
        replace: '***'

    static_configs:
      - targets:
         - localhost
        labels:
         job: nginx_access_log
         host: nginx
         agent: promtail
         __path__: /var/log/nginx/*access.log

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
