export { default as AddCategoryModal } from "./ui/AddCategory";
export { default as EditCategoryModal } from "./ui/EditCategory";
export { default as AddNomenclatureModal } from "./ui/AddNomenclature";
export { default as EditNomenclatureModal } from "./ui/EditNomenclature";
export { default as AddOrganizations } from "./ui/AddOrganizations";
export { default as EditOrganizations } from "./ui/EditOrganizations";
export { default as EditContracts } from "./ui/EditContracts";
export { default as AddContracts } from "./ui/AddContracts";
export { default as EditWarehouses } from "./ui/EditWarehouses";
export { default as AddWarehouses } from "./ui/AddWarehouses";
export { default as AddWarehousesDocs } from "./ui/AddWarehousesDocs";
export { default as EditWarehousesDocs } from "./ui/EditWarehousesDocs";
export { default as AddDocsPutchases } from "./ui/AddDocsPurchases";
export { default as EditDocsPurchasesModal } from "./ui/EditDocsPurchases"
export { default as AddPrice } from "./ui/AddPrice";
export { default as EditPrice } from "./ui/EditPrice";
export { default as AddLoyalitySetting } from "./ui/AddLoyalitySetting";
export { default as EditLoyalitySetting } from "./ui/EditLoyalitySetting";
